### ISSUE TITLE
RotationSpeed: value=None is not a numeric value.

### ISSUE THREAD

**Issue by RnJ4** [Hcreak/HomeKit-MiAcPartnerMcn02#1]
Traceback (most recent call last):
  File "main.py", line 152, in <module>
    driver.add_accessory(accessory=get_accessory(driver))
  File "main.py", line 145, in get_accessory
    return XiaoMiAcPartnerMcn02(driver, 'MyAcPartner')
  File "main.py", line 101, in __init__
    self.char_fanspeed.set_value(miio_get_fanspeed())
  File "/usr/local/lib/python3.7/dist-packages/pyhap/characteristic.py", line 200, in set_value
    value = self.to_valid_value(value)
  File "/usr/local/lib/python3.7/dist-packages/pyhap/characteristic.py", line 149, in to_valid_value
    raise ValueError(error_msg)
ValueError: RotationSpeed: value=None is not a numeric value.

**Comment by RnJ4** [comment]
检查了一下，是miio没能够执行命令
Error: {'code': -9999, 'message': 'user ack timeout'}
但是token是对的，能获取用户信息，太迷了

**Comment by RnJ4** [comment]
发现问题了，我的空调在设置成抽湿模式时，无法调节风速，所以获取不到这个参数

**Comment by Hcreak** [comment]
抱歉我没有及时看到这个issue 我打算在下一个版本中将 `service`  类型改为 `Thermostat` 以解决使用`Siri`调节温度模式错乱的问题 但这将失去风量调节和扫风开关 `HeaterCooler`类型版本将停止支持 但我将会把他放到`HeaterCooler`分支
