### ISSUE TITLE
AttributeError: module 'miio' has no attribute 'airconditioningcompanionMCN'

### ISSUE THREAD

**Issue by KevinDevs** [Hcreak/HomeKit-MiAcPartnerMcn02#2]
Traceback (most recent call last):
  File "./main.py", line 4, in <module>
    from miio_wrapper import *
  File "/root/HomeKit-MiAcPartnerMcn02-master/miio_wrapper.py", line 6, in <module>
    target = miio.airconditioningcompanionMCN.AirConditioningCompanionMcn02(
AttributeError: module 'miio' has no attribute 'airconditioningcompanionMCN'

python新手..看不出来问题

**Comment by KevinDevs** [comment]
hmm把miio.airconditioningcompanionMCN.AirConditioningCompanionMcn02 改成 miio.airconditioningcompanion.AirConditioningCompanion就好了
