### ISSUE TITLE
macvlan部署时无法与设备连接

### ISSUE THREAD

**Issue by XiaoTonyLuo** [Hcreak/HomeKit-MiAcPartnerMcn02#4]
直接在raspberry上部署成功添加到homekit，使用docker macvlan部署时报错无法与设备连接

```bash
pi@raspberrypi:/home/HomeKit-MiAcPartnerMcn02 $ docker container logs ce4aab457c48
 * Serving Flask app 'webshow' (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
[_internal]  * Running on all addresses.
   WARNING: This is a development server. Do not use it in a production deployment.
[_internal]  * Running on http://10.10.10.200:5000/ (Press CTRL+C to quit)
Traceback (most recent call last):
  File "main.py", line 114, in <module>
    driver.add_accessory(accessory=get_accessory(driver))
  File "main.py", line 99, in get_accessory
    return XiaoMiAcPartnerMcn02(driver, 'MyAcPartner')
  File "main.py", line 37, in __init__
    'TargetHeatingCoolingState', value=miio_get_mode_new(),
  File "/app/miio_wrapper.py", line 84, in miio_get_mode_new
    result = target.raw_command("get_prop",["power","mode"])
  File "/usr/local/lib/python3.8/site-packages/miio/device.py", line 197, in raw_command
    return self.send(command, parameters)
  File "/usr/local/lib/python3.8/site-packages/miio/device.py", line 178, in send
    return self._protocol.send(
  File "/usr/local/lib/python3.8/site-packages/miio/miioprotocol.py", line 161, in send
    self.send_handshake()
  File "/usr/local/lib/python3.8/site-packages/miio/miioprotocol.py", line 74, in send_handshake
    raise DeviceException("Unable to discover the device %s" % self.ip)
miio.exceptions.DeviceException: Unable to discover the device 192.168.50.10
```

docker macvlan配置
``` bash
pi@raspberrypi:/home/HomeKit-MiAcPartnerMcn02 $ docker network inspect d45f5d7af689
[
    {
        "Name": "mvc0",
        "Id": "d45f5d7af689a8d86f55eaf7492af22a8f0532a18bdc6cf4c7a706f067bd012f",
        "Created": "2021-06-28T15:08:34.615809303+01:00",
        "Scope": "local",
        "Driver": "macvlan",
        "EnableIPv6": false,
        "IPAM": {
            "Driver": "default",
            "Options": {},
            "Config": [
                {
                    "Subnet": "10.10.10.0/24",
                    "IPRange": "10.10.10.200/29",
                    "Gateway": "10.10.10.1"
                }
            ]
        },
        "Internal": false,
        "Attachable": false,
        "Ingress": false,
        "ConfigFrom": {
            "Network": ""
        },
        "ConfigOnly": false,
        "Containers": {},
        "Options": {
            "parent": "eth0"
        },
        "Labels": {}
    }
]
```

树莓派ifconfig
```bash 
pi@raspberrypi:/home/HomeKit-MiAcPartnerMcn02 $ ifconfig -a
docker0: flags=4099<UP,BROADCAST,MULTICAST>  mtu 1500
        inet 172.17.0.1  netmask 255.255.0.0  broadcast 172.17.255.255
        inet6 fe80::42:2aff:fe29:8291  prefixlen 64  scopeid 0x20<link>
        ether 02:42:2a:29:82:91  txqueuelen 0  (Ethernet)
        RX packets 6761  bytes 408947 (399.3 KiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 24703  bytes 120260838 (114.6 MiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

eth0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.168.50.185  netmask 255.255.255.0  broadcast 192.168.50.255
        inet6 fd99:2f96:152e:3:f57e:ec0a:a130:47d2  prefixlen 64  scopeid 0x0<global>
        inet6 fe80::217c:7992:ee2a:c7b4  prefixlen 64  scopeid 0x20<link>
        ether dc:a6:32:ca:92:26  txqueuelen 1000  (Ethernet)
        RX packets 101013  bytes 127696970 (121.7 MiB)
        RX errors 0  dropped 6  overruns 0  frame 0
        TX packets 23555  bytes 7619041 (7.2 MiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
        inet 127.0.0.1  netmask 255.0.0.0
        inet6 ::1  prefixlen 128  scopeid 0x10<host>
        loop  txqueuelen 1000  (Local Loopback)
        RX packets 55  bytes 21346 (20.8 KiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 55  bytes 21346 (20.8 KiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

wlan0: flags=4099<UP,BROADCAST,MULTICAST>  mtu 1500
        ether dc:a6:32:ca:92:27  txqueuelen 1000  (Ethernet)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 0  bytes 0 (0.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
```

**Comment by XiaoTonyLuo** [comment]
macvlan创建时网段填写错误，修改为本地网段后问题解决。
